In [1]:
import pandas as pd

In [6]:
health = pd.read_csv("health.csv", encoding = "utf-8")
health.head()

    지역  현재흡연율  현재흡연자의 금연시도율  고위험음주율  스트레스 인지율
0  종로구   20.4          35.2    20.1      25.4
1   중구   22.2          26.9    20.3      28.6
2  용산구   19.5          31.9    18.9      28.7
3  성동구   20.5          39.3    16.2      28.4
4  광진구   19.4          30.9    17.0      30.4

In [31]:
number = pd.read_csv('number.csv', encoding ='utf-8')
number

,구분,계,1인가구,2인가구,3인가구,4인가구,5인 가구,6인가구,7인이상 가구
0,합계,"3,784,705","1,138,860","931,262","816,946","686,469","163,555","37,153","10,460"
1,종로구,"60,786","22,835","14,974","11,060","8,712","2,397",618,190
2,중구,"51,503","19,671","13,086","9,453","6,844","1,836",480,133
3,용산구,"90,164","31,641","23,505","17,580","13,121","3,327",780,210
4,성동구,"116,401","37,074","28,668","24,655","19,874","4,636","1,164",330
5,광진구,"146,196","53,169","33,221","28,757","24,040","5,430","1,202",377
6,동대문구,"145,179","52,650","34,094","27,768","22,627","6,011","1,584",445
7,중랑구,"157,571","45,717","40,865","34,515","27,503","6,971","1,569",431
8,성북구,"174,370","54,117","41,498","36,906","31,578","7,791","1,915",565
9,강북구,"125,580","36,668","33,636","27,243","20,969","5,386","1,294",384
10,도봉구,"125,384","28,296","33,279","30,449","25,702","5,900","1,375",383
11,노원구,"204,606","47,641","50,338","49,255","45,404","9,675","1,867",426
12,은평구,"178,775","44,440","48,170","41,213","33,726","8,626","2,032",568
13,서대문구,"126,581","43,298","30,769","25,336","20,559","5,042","1,224",353
14,마포구,"153,610","53,382","37,837","30,533","24,334","5,892","1,268",364
15,양천구,"163,253","32,878","38,620","41,654","39,182","8,640","1,798",481
16,강서구,"222,652","60,988","56,504","50,606","42,042","9,837","2,085",590
17,구로구,"156,671","42,055","39,875","35,273","29,972","7,283","1,723",490
18,금천구,"93,402","31,728","22,652","19,110","15,034","3,745",864,269
19,영등포구,"146,904","49,453","35,972","30,397","23,867","5,544","1,306",365
20,동작구,"159,770","52,954","38,396","32,979","27,152","6,401","1,483",405
21,관악구,"230,570","103,972","51,679","37,389","28,357","6,997","1,692",484
22,서초구,"155,051","38,357","37,334","36,130","32,862","8,068","1,728",572
23,강남구,"208,904","61,998","50,447","45,353","39,694","8,984","1,893",535
24,송파구,"230,801","54,409","56,203","55,774","50,122","11,184","2,462",647
25,강동구,"160,021","39,469","39,640","37,558","33,192","7,952","1,747",463

In [38]:
number['1인가구비율'] = number['1인가구'] + number['계']
number

,구분,계,1인가구,2인가구,3인가구,4인가구,5인 가구,6인가구,7인이상 가구,1인가구비율
0,합계,"3,784,705","1,138,860","931,262","816,946","686,469","163,555","37,153","10,460","1,138,8603,784,705"
1,종로구,"60,786","22,835","14,974","11,060","8,712","2,397",618,190,"22,83560,786"
2,중구,"51,503","19,671","13,086","9,453","6,844","1,836",480,133,"19,67151,503"
3,용산구,"90,164","31,641","23,505","17,580","13,121","3,327",780,210,"31,64190,164"
4,성동구,"116,401","37,074","28,668","24,655","19,874","4,636","1,164",330,"37,074116,401"
5,광진구,"146,196","53,169","33,221","28,757","24,040","5,430","1,202",377,"53,169146,196"
6,동대문구,"145,179","52,650","34,094","27,768","22,627","6,011","1,584",445,"52,650145,179"
7,중랑구,"157,571","45,717","40,865","34,515","27,503","6,971","1,569",431,"45,717157,571"
8,성북구,"174,370","54,117","41,498","36,906","31,578","7,791","1,915",565,"54,117174,370"
9,강북구,"125,580","36,668","33,636","27,243","20,969","5,386","1,294",384,"36,668125,580"
10,도봉구,"125,384","28,296","33,279","30,449","25,702","5,900","1,375",383,"28,296125,384"
11,노원구,"204,606","47,641","50,338","49,255","45,404","9,675","1,867",426,"47,641204,606"
12,은평구,"178,775","44,440","48,170","41,213","33,726","8,626","2,032",568,"44,440178,775"
13,서대문구,"126,581","43,298","30,769","25,336","20,559","5,042","1,224",353,"43,298126,581"
14,마포구,"153,610","53,382","37,837","30,533","24,334","5,892","1,268",364,"53,382153,610"
15,양천구,"163,253","32,878","38,620","41,654","39,182","8,640","1,798",481,"32,878163,253"
16,강서구,"222,652","60,988","56,504","50,606","42,042","9,837","2,085",590,"60,988222,652"
17,구로구,"156,671","42,055","39,875","35,273","29,972","7,283","1,723",490,"42,055156,671"
18,금천구,"93,402","31,728","22,652","19,110","15,034","3,745",864,269,"31,72893,402"
19,영등포구,"146,904","49,453","35,972","30,397","23,867","5,544","1,306",365,"49,453146,904"
20,동작구,"159,770","52,954","38,396","32,979","27,152","6,401","1,483",405,"52,954159,770"
21,관악구,"230,570","103,972","51,679","37,389","28,357","6,997","1,692",484,"103,972230,570"
22,서초구,"155,051","38,357","37,334","36,130","32,862","8,068","1,728",572,"38,357155,051"
23,강남구,"208,904","61,998","50,447","45,353","39,694","8,984","1,893",535,"61,998208,904"
24,송파구,"230,801","54,409","56,203","55,774","50,122","11,184","2,462",647,"54,409230,801"
25,강동구,"160,021","39,469","39,640","37,558","33,192","7,952","1,747",463,"39,469160,021"